export * from './CourseHeavyDTO.js';
export * from './CourseInDTO.js';
export * from './CourseLightDTO.js';
export * from './CourseUpdateDTO.js';
export * from './FavoriteCourseInDTO.js';
export * from './FavoriteCourseOutDTO.js';
export * from './InscriptionCourseInDTO.js';
export * from './InscriptionCourseOutDTO.js';
export * from './InscriptionCourseUpdateDTO.js';
