export enum SORT_COURSES {
  TITLE = 'TITLE',
  LEVEL = 'LEVEL',
  STATUS = 'STATUS',
  ACTIVE = 'ACTIVE',
  AI_GENERATED = 'AI_GENERATED',
  PRICE = 'PRICE',
  AVERAGE_REVIEWS = 'AVERAGE_REVIEWS',
  DURATION_HOURS = 'DURATION_HOURS',
  TOTAL_LESSONS = 'TOTAL_LESSONS',
  TOTAL_REVIEWS = 'TOTAL_REVIEWS',
  TOTAL_ENROLLMENTS = 'TOTAL_ENROLLMENTS',
  CREATION_DATE = 'CREATION_DATE',
  LAST_UPDATE = 'LAST_UPDATE',
  PUBLISHING_DATE = 'PUBLISHING_DATE',
  LAST_AI_UPDATE = 'LAST_AI_UPDATE',
}
export enum SORT_INSCRIPTION {
  COMPLETED = 'COMPLETED',
  CREATION_DATE = 'CREATION_DATE',
  PROGRESS_PERCENTAGE = 'PROGRESS_PERCENTAGE',
  SCORE = 'SCORE',
  ACTIVE = 'ACTIVE',
}
export enum SORT_FAVORITE_COURSE {
  CREATION_DATE = 'CREATION_DATE',
  TITLE = 'TITLE',
  AVERAGE_REVIEWS = 'AVERAGE_REVIEWS',
  TOTAL_ENROLLMENTS = 'TOTAL_ENROLLMENTS',
  LEVEL = 'LEVEL',
}
export enum SORT_TAG {
  CREATION_DATE = 'CREATION_DATE',
  NAME = 'NAME',
}
export enum SORT_LESSON {
  TITLE = 'TITLE',
  DURATION_MINUTES = 'DURATION_MINUTES',
  CREATION_DATE = 'CREATION_DATE',
  ACTIVE = 'ACTIVE',
  ORDER = 'ORDER',
  AI_GENERATED = 'AI_GENERATED',
  ESTIMATED_DIFFICULTY = 'ESTIMATED_DIFFICULTY',
  LESSON_TYPE = 'LESSON_TYPE',
}
export enum SORT_SUBMISSION {
  ACTIVE = 'ACTIVE',
  SCORE = 'SCORE',
  STATUS = 'STATUS',
  SUBMISSION_DATE = 'SUBMISSION_DATE',
  GRADING_DATE = 'GRADING_DATE',
}
export enum SORT_QUIZ_SECTION {
  AI_GENERATED = 'AI_GENERATED',
  CREATION_DATE = 'CREATION_DATE',
  ACTIVE = 'ACTIVE',
  DURATION_MINUTES = 'DURATION_MINUTES',
  TITLE = 'TITLE',
}
export enum SORT_CATEGORY {
  NAME = 'NAME',
  ACTIVE = 'ACTIVE',
}
export enum SORT_SECTION {
  TITLE = 'TITLE',
  DURATION_HOURS = 'DURATION_HOURS',
  CREATION_DATE = 'CREATION_DATE',
  ACTIVE = 'ACTIVE',
  ORDER = 'ORDER',
  AI_GENERATED = 'AI_GENERATED',
  SUGGESTED_BY_AI = 'SUGGESTED_BY_AI',
}
export enum SORT_ASSIGNMENT {
  TITLE = 'TITLE',
  MAX_FILE_SIZE_MB = 'MAX_FILE_SIZE_MB',
  ALLOWED_TYPES = 'ALLOWED_TYPES',
  DUE_DATE = 'DUE_DATE',
  MAX_SCORE = 'MAX_SCORE',
  ACTIVE = 'ACTIVE',
  CREATION_DATE = 'CREATION_DATE',
}
export enum SORT_LESSON_CONTENT {
  VERSION = 'VERSION',
  ACTIVE = 'ACTIVE',
  DIFFICULTY_LEVEL = 'DIFFICULTY_LEVEL',
  LEARNING_TECHNIQUE = 'LEARNING_TECHNIQUE',
  ORDER_PREFERENCE = 'ORDER_PREFERENCE',
  CREATION_DATE = 'CREATION_DATE',
  AI_GENERATED = 'AI_GENERATED',
  CONTENT_TYPE = 'CONTENT_TYPE',
}
export enum SORT_PROGRESS_CONTENT {
  START_DATE = 'START_DATE',
  COMPLETED_DATE = 'COMPLETED_DATE',
  EFFECTIVINESS_SCORE = 'EFFECTIVINESS_SCORE',
  ACTIVE = 'ACTIVE',
  USER_RATING = 'USER_RATING',
  TIME_SPEND_MINUTES = 'TIME_SPEND_MINUTES',
  COMPLETION_PERCENTAGE = 'COMPLETION_PERCENTAGE',
}
export enum SORT_AI_SPECS_LESSON {
  CREATION_DATE = 'CREATION_DATE',
  ESTIMATED_VIDEO_DURATION = 'ESTIMATED_VIDEO_DURATION',
}
export enum SORT_ATTEMPT_QUIZ {
  SUBMISSION_DATE = 'SUBMISSION_DATE',
  DURATION_MINUTES = 'DURATION_MINUTES',
  GRADE = 'GRADE',
}
export enum SORT_QUESTION_QUIZ {
  QUESTION = 'QUESTION',
  DURATION_MINUTES = 'DURATION_MINUTES',
}
export enum SORT_RESOURCE {
  TYPE = 'TYPE',
  DISCRIMINANT_RESOURCE = 'DISCRIMINANT_RESOURCE',
  NAME = 'NAME',
  ORDER = 'ORDER',
  DURATION_SECONDS = 'DURATION_SECONDS',
  FILE_SIZE_MB = 'FILE_SIZE_MB',
}
export enum SORT_OPTION_QUIZ {
  OPTION = 'OPTION',
}
