export * from './aispecs.js';
export * from './assignments.js';
export * from './categories.js';
export * from './courses.js';
export * from './lessons.js';
export * from './quizzes.js';
export * from './resources.js';
export * from './sections.js';
export * from './tags.js';
